name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "(Merge branch 'master' into .+|\[#\d+\] - .+$)"
          flags: 'g'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          error: 'The commit message should be formatted as "[#TASK_ID] - message"'
      - name: Check current branch name
        shell: python
        run: |
          import os
          import re
          branch = os.getenv('GITHUB_HEAD_REF')
          assert re.match(r"^[\d|\w]+/#\d+-.+", branch), 'The branch should be formatted as "type/#TASK_ID-description" but received {}'.format(branch)
          print('"{}" branch is successfully checked'.format(branch))